-- DDL Script for database schema
CREATE TABLE CAR_CATEGORY (
                CAR_CATEGORY_ID CHAR(5) NOT NULL,
                CAR_CATEGORY_NAME VARCHAR2(30) NOT NULL,
                CONSTRAINT CAR_CATEGORY_PK PRIMARY KEY (CAR_CATEGORY_ID)
);


CREATE TABLE CUSTOMER (
                CUSTOMER_ID NUMBER(7) NOT NULL,
                CUSTOMER_CPR NUMBER(9),
                CUSTOMER_PASSPORT_NUMBER VARCHAR2(30),
                CUSTOMER_FIRST_NAME VARCHAR2(40) NOT NULL,
                CUSTOMER_LAST_NAME VARCHAR2(40) NOT NULL,
                CUSTOMER_PHONE_NUMBER VARCHAR2(30) NOT NULL,
                CUSTOMER_EMAIL VARCHAR2(60) NOT NULL,
                CUSTOMER_BLD VARCHAR2(30) NOT NULL,
                CUSTOMER_STREET VARCHAR2(30) NOT NULL,
                CUSTOMER_BLOCK VARCHAR2(30) NOT NULL,
                CUSTOMER_CITY VARCHAR2(30) NOT NULL,
                CONSTRAINT CUSTOMER_PK PRIMARY KEY (CUSTOMER_ID)
);


CREATE TABLE EXTRA_EQUIPMENT (
                EQUIPMENT_ID NUMBER(7) NOT NULL,
                EQUIPMENT_NAME VARCHAR2(40) NOT NULL,
                EQUIPMENT_STOCK NUMBER(4) NOT NULL,
                EQUIPMENT_DAILY_PRICE NUMBER(6,3) NOT NULL,
                EQUIPMENT_DESCRIPTION VARCHAR2(700) NOT NULL,
                CONSTRAINT EXTRA_EQUIPMENT_PK PRIMARY KEY (EQUIPMENT_ID)
);


CREATE TABLE MANUFACTURER (
                MANUFACTURER_ID NUMBER(7) NOT NULL,
                MANUFACTURER_NAME VARCHAR2(30) NOT NULL,
                MANUFACTURER_COUNTRY VARCHAR2(30) NOT NULL,
                CONSTRAINT MANUFACTURER_PK PRIMARY KEY (MANUFACTURER_ID)
);


CREATE TABLE CAR_MODEL (
                MODEL_ID NUMBER(7) NOT NULL,
                MODEL_NAME VARCHAR2(50) NOT NULL,
                MODEL_ENGINE_SIZE NUMBER(5) NOT NULL,
                CAR_CATEGORY_ID CHAR(5) NOT NULL,
                MANUFACTURER_ID NUMBER(7) NOT NULL,
                CONSTRAINT CAR_MODEL_PK PRIMARY KEY (MODEL_ID)
);


CREATE TABLE LOCATION (
                LOCATION_ID NUMBER(7) NOT NULL,
                LOCATION_CITY VARCHAR2(30) NOT NULL,
                LOCATION_BLD NUMBER(5) NOT NULL,
                LOCATION_STREET VARCHAR2(40) NOT NULL,
                LOCATION_BLOCK NUMBER(5) NOT NULL,
                LOCATION_PHONE_NUMBER NUMBER(8) NOT NULL,
                CONSTRAINT LOCATION_PK PRIMARY KEY (LOCATION_ID)
);


CREATE TABLE EMPLOYEE (
                EMPLOYEE_ID NUMBER(7) NOT NULL,
                EMPLOYEE_CPR NUMBER(9) NOT NULL,
                EMPLOYEE_FIRST_NAME VARCHAR2(40) NOT NULL,
                EMPLOYEE_LAST_NAME VARCHAR2(40) NOT NULL,
                EMPLOYEE_DOB DATE NOT NULL,
                EMPLOYEE_PHONE_NUMBER VARCHAR2(20) NOT NULL,
                EMPLOYEE_EMAIL VARCHAR2(50) NOT NULL,
                EMPLOYEE_BLD VARCHAR2(30) NOT NULL,
                EMPLOYEE_STREET VARCHAR2(30) NOT NULL,
                EMPLOYEE_BLOCK VARCHAR2(30) NOT NULL,
                EMPLOYEE_CITY VARCHAR2(30) NOT NULL,
                LOCATION_ID NUMBER(7) NOT NULL,
                EMPLOYEE_HIRE_DATE DATE NOT NULL,
                JOB_TITLE VARCHAR2(35) NOT NULL,
                EMPLOYEE_SALARY NUMBER(6) NOT NULL,
                MANAGER_ID NUMBER(7),
                CONSTRAINT EMPLOYEE_PK PRIMARY KEY (EMPLOYEE_ID)
);


CREATE TABLE CAR (
                CAR_ID NUMBER(7) NOT NULL,
                REG_PLATE_NUMBER NUMBER(8) NOT NULL,
                CAR_YEAR_MANUFACTURED NUMBER(4) NOT NULL,
                CAR_REGISTRATION_DUE_DATE DATE NOT NULL,
                CAR_COLOR VARCHAR2(20) NOT NULL,
                CAR_CURRENT_MILAGE NUMBER(10,2) NOT NULL,
                CAR_DAILY_HIRE_RATE NUMBER(6,3) NOT NULL,
                CAR_DAILY_PENALTY_RATE NUMBER(6,3) NOT NULL,
                CAR_STATUS VARCHAR2(30) NOT NULL,
                MODEL_ID NUMBER(7) NOT NULL,
                LOCATION_ID NUMBER(7) NOT NULL,
                CONSTRAINT CAR_PK PRIMARY KEY (CAR_ID)
);


CREATE TABLE RENTAL (
                RENTAL_ID NUMBER(7) NOT NULL,
                CUSTOMER_ID NUMBER(7) NOT NULL,
                CAR_ID NUMBER(7) NOT NULL,
                RENTAL_START_DATE DATE NOT NULL,
                RENTAL_END_DATE DATE NOT NULL,
                ACTUAL_RETURN_DATE DATE,
                RENTAL_STATUS VARCHAR2(30) NOT NULL,
                CONSTRAINT RENTAL_PK PRIMARY KEY (RENTAL_ID)
);


CREATE TABLE INVOICE (
                INVOICE_ID NUMBER(7) NOT NULL,
                RENTAL_ID NUMBER(7) NOT NULL,
                RENTAL_COST NUMBER(7,3) NOT NULL,
                EXTRA_EQUIPMENTS_COST NUMBER(7,3) NOT NULL,
                LATE_PENALTY_COST NUMBER(7,3),
                TOTAL_AMOUNT NUMBER(7,3) NOT NULL,
                DISCOUNT_AMOUNT NUMBER(6,3) NOT NULL,
                VAT NUMBER(6,3) NOT NULL,
                TOTAL_PAYABLE_AMOUNT NUMBER(7,3) NOT NULL,
                PAYMENT_STATUS VARCHAR2(30) NOT NULL,
                PAYMENT_METHOD VARCHAR2(40),
                PAYMENT_DATE DATE,
                CONSTRAINT INVOICE_PK PRIMARY KEY (INVOICE_ID)
);


CREATE TABLE RENTAL_EQUIPMENT (
                RENTAL_ID NUMBER(7) NOT NULL,
                EQUIPMENT_ID NUMBER(7) NOT NULL,
                QUANTITY NUMBER(3) NOT NULL,
                CONSTRAINT RENTAL_EQUIPMENT_PK PRIMARY KEY (RENTAL_ID, EQUIPMENT_ID)
);


CREATE TABLE INSURANCE_HISTORY (
                INSURANCE_HISTORY_ID NUMBER(7) NOT NULL,
                CAR_ID NUMBER(7) NOT NULL,
                INSURANCE_COMPANY VARCHAR2(60) NOT NULL,
                INSURANCE_START_DATE DATE NOT NULL,
                INSURANCE_DUE_DATE DATE NOT NULL,
                INSURANCE_COST NUMBER(7,3) NOT NULL,
                INSURANCE_TYPE VARCHAR2(30) NOT NULL,
                CONSTRAINT INSURANCE_HISTORY_PK PRIMARY KEY (INSURANCE_HISTORY_ID)
);


CREATE TABLE MAINTENANCE_HISTORY (
                MAINTENANCE_ID NUMBER(7) NOT NULL,
                CAR_ID NUMBER(7) NOT NULL,
                MAINTENANCE_DATE DATE NOT NULL,
                MAINTENANCE_COST NUMBER(7,3),
                MAINTENANCE_DESCRIPTION VARCHAR2(100),
                MAINTENANCE_PLACE VARCHAR2(50),
                CONSTRAINT MAINTENANCE_HISTORY_PK PRIMARY KEY (MAINTENANCE_ID)
);


ALTER TABLE CAR_MODEL ADD CONSTRAINT CAR_MODEL_CATEGORY_FK
FOREIGN KEY (CAR_CATEGORY_ID)
REFERENCES CAR_CATEGORY (CAR_CATEGORY_ID)
NOT DEFERRABLE;

ALTER TABLE RENTAL ADD CONSTRAINT RENTAL_CUSTOMER_FK
FOREIGN KEY (CUSTOMER_ID)
REFERENCES CUSTOMER (CUSTOMER_ID)
NOT DEFERRABLE;

ALTER TABLE RENTAL_EQUIPMENT ADD CONSTRAINT RENTAL_EXTRA_EQUIPMENT_FK
FOREIGN KEY (EQUIPMENT_ID)
REFERENCES EXTRA_EQUIPMENT (EQUIPMENT_ID)
NOT DEFERRABLE;

ALTER TABLE CAR_MODEL ADD CONSTRAINT CAR_MODEL_MANUFACTURER_FK
FOREIGN KEY (MANUFACTURER_ID)
REFERENCES MANUFACTURER (MANUFACTURER_ID)
NOT DEFERRABLE;

ALTER TABLE CAR ADD CONSTRAINT CAR_MODEL_FK
FOREIGN KEY (MODEL_ID)
REFERENCES CAR_MODEL (MODEL_ID)
NOT DEFERRABLE;

ALTER TABLE CAR ADD CONSTRAINT CAR_LOCATION_FK
FOREIGN KEY (LOCATION_ID)
REFERENCES LOCATION (LOCATION_ID)
NOT DEFERRABLE;

ALTER TABLE EMPLOYEE ADD CONSTRAINT EMPLOYEE_LOCATION_FK
FOREIGN KEY (LOCATION_ID)
REFERENCES LOCATION (LOCATION_ID)
NOT DEFERRABLE;

ALTER TABLE EMPLOYEE ADD CONSTRAINT EMPLOYEE_MANAGER_ID_FK
FOREIGN KEY (MANAGER_ID)
REFERENCES EMPLOYEE (EMPLOYEE_ID)
NOT DEFERRABLE;

ALTER TABLE MAINTENANCE_HISTORY ADD CONSTRAINT MAINTENANCE_HISTORY_CAR_FK
FOREIGN KEY (CAR_ID)
REFERENCES CAR (CAR_ID)
NOT DEFERRABLE;

ALTER TABLE INSURANCE_HISTORY ADD CONSTRAINT INSURANCE_HISTORY_CAR_FK
FOREIGN KEY (CAR_ID)
REFERENCES CAR (CAR_ID)
NOT DEFERRABLE;

ALTER TABLE RENTAL ADD CONSTRAINT RENTAL_CAR_FK
FOREIGN KEY (CAR_ID)
REFERENCES CAR (CAR_ID)
NOT DEFERRABLE;

ALTER TABLE RENTAL_EQUIPMENT ADD CONSTRAINT RENTAL_EQUIPMENT_RENTAL_FK
FOREIGN KEY (RENTAL_ID)
REFERENCES RENTAL (RENTAL_ID)
NOT DEFERRABLE;

ALTER TABLE INVOICE ADD CONSTRAINT INVOICE_RENTAL_FK
FOREIGN KEY (RENTAL_ID)
REFERENCES RENTAL (RENTAL_ID)
NOT DEFERRABLE;

ALTER TABLE CAR ADD CONSTRAINT CAR_STATUS_CHECK
CHECK ( CAR_STATUS IN ('Rented','Available','Under Maintenance') );

ALTER TABLE INVOICE ADD CONSTRAINT PAYMENT_STATUS_CHECK
CHECK ( PAYMENT_STATUS IN ('Completed','Pending') );

ALTER TABLE RENTAL ADD CONSTRAINT RENTAL_STATUS_CHECK
CHECK ( RENTAL_STATUS IN ('Completed','Cancelled','Confirmed','On-going') );

ALTER TABLE CAR ADD CONSTRAINT CAR_PENALTY_RATE_CHECK
CHECK ( CAR_DAILY_PENALTY_RATE <= (CAR_DAILY_HIRE_RATE*0.1) );
