-- Package Specification For INVOICE_PKG -- 
CREATE OR REPLACE PACKAGE INVOICE_PKG AS

PROCEDURE PR_CREATE_RENTAL_INVOICE (RENTALID IN NUMBER,DIS_RATE IN NUMBER,PAY_METHOD IN VARCHAR);

END INVOICE_PKG;
/


-- Package Body for INVOICE_PKG -- 
CREATE OR REPLACE PACKAGE BODY INVOICE_PKG AS
-- Private Functions that do calculations

-- A FUNCTION TO CALCUALTE DURATION BETWEEN TWO DATES
FUNCTION CALCULATE_DURATION (START_DATE IN DATE,END_DATE IN DATE) RETURN NUMBER
IS
    NUM_OF_DAYS  NUMBER;
BEGIN 
    NUM_OF_DAYS := END_DATE - START_DATE;
    RETURN NUM_OF_DAYS;
END CALCULATE_DURATION;

-- A FUNCTION TO CALCULATE RENTAL COST WITHIN GIVEN PERIOD AND DAILY RATE
FUNCTION CALCULATE_RENTAL_COST (V_PERIOD IN NUMBER,V_RATE IN NUMBER) RETURN NUMBER
IS
    V_COST  NUMBER(10,3);
BEGIN 
    V_COST := V_PERIOD * V_RATE;
    RETURN V_COST;
END CALCULATE_RENTAL_COST;

-- A FUNCTION TO CALCULATE LATE PENALTY COST
FUNCTION CALCULATE_LATE_PENANLTY_COST (V_LATE_DURATION IN NUMBER,V_LATE_RATE IN NUMBER) RETURN NUMBER
IS
    V_LCOST  NUMBER(6,3);
BEGIN 
    V_LCOST := V_LATE_DURATION * V_LATE_RATE;
    RETURN V_LCOST;
END CALCULATE_LATE_PENANLTY_COST;

-- A FUNCTION TO CALCULATE EXTRA EQUIPMENT COST FOR CERTAIN RENTAL
FUNCTION CALCUALTE_EX_EQUIPMENT_COST (RENTALID IN NUMBER) RETURN NUMBER
IS
    CURSOR EXTRA_EQUIP IS 
    SELECT RE.EQUIPMENT_ID,RE.QUANTITY,E.EQUIPMENT_DAILY_PRICE
    FROM RENTAL_EQUIPMENT RE, EXTRA_EQUIPMENT E
    WHERE RE.EQUIPMENT_ID = E.EQUIPMENT_ID AND
    RENTALID  = RE.RENTAL_ID;
    START_DATE DATE;
    END_DATE DATE;
    NUM_OF_EQUIPMENT NUMBER;
    V_DURATION NUMBER;
    V_EXTRA_EQUIPMENT_COST NUMBER :=0;
BEGIN 
 SELECT COUNT (*) INTO NUM_OF_EQUIPMENT FROM RENTAL_EQUIPMENT WHERE RENTALID = RENTAL_ID;
    IF NUM_OF_EQUIPMENT > 0 THEN
    SELECT RENTAL_START_DATE,ACTUAL_RETURN_DATE INTO START_DATE, END_DATE FROM RENTAL WHERE RENTAL_ID = RENTALID;
    V_DURATION := CALCULATE_DURATION (START_DATE, END_DATE);
    FOR EQUIPMENT_RECORD IN EXTRA_EQUIP
    LOOP
    V_EXTRA_EQUIPMENT_COST := V_EXTRA_EQUIPMENT_COST + (EQUIPMENT_RECORD.QUANTITY*V_DURATION);
    END LOOP;
    END IF;
    RETURN V_EXTRA_EQUIPMENT_COST;
END CALCUALTE_EX_EQUIPMENT_COST;

-- A FUNCTION TO CALCUALTE COST AFTER DISCOUNT
FUNCTION CALCUALTE_COST_AFTER_DISCOUNT (V_COST IN NUMBER,V_DIS_RATE IN NUMBER) RETURN NUMBER
IS
    V_COST_AFTER_DISCOUNT  NUMBER(10,3);
BEGIN 
    V_COST_AFTER_DISCOUNT := V_COST - (V_COST*V_DIS_RATE);
    RETURN V_COST_AFTER_DISCOUNT;
END CALCUALTE_COST_AFTER_DISCOUNT;

-- A FUNCTION TO CALCUALTE COST AFTER VAT
FUNCTION CALCUALTE_COST_AFTER_VAT (V_COST IN NUMBER,V_VAT_RATE IN NUMBER) RETURN NUMBER
IS
    V_COST_AFTER_VAT  NUMBER(10,3);
BEGIN 
    V_COST_AFTER_VAT := V_COST + (V_COST*V_VAT_RATE);
    RETURN V_COST_AFTER_VAT;
END CALCUALTE_COST_AFTER_VAT;

-- Public PROCEDURE TO CREATE RENATL INVOICE
PROCEDURE PR_CREATE_RENTAL_INVOICE (RENTALID IN NUMBER,DIS_RATE IN NUMBER,PAY_METHOD IN VARCHAR)
AS
START_DATE DATE;
END_DATE DATE;
ACTUAL_END_DATE DATE;
CARID NUMBER;
CAR_HIRE_RATE NUMBER;
LATE_RATE NUMBER;
EX_EQUIPMENT_COST NUMBER := 0;
R_DURATION NUMBER;
RENTAL_COST NUMBER:=0;
LATE_DURATION NUMBER:=0;
LATE_AMOUNT NUMBER := 0; 
TOTAL_AMOUNT NUMBER := 0;
VAT_RATE NUMBER :=0.1;
TOTAL_P_AMOUNT NUMBER:=0;
PAY_STATUS VARCHAR2(50):='Completed';
PAYMENT_DATE DATE;
BEGIN

    SELECT RENTAL_START_DATE,RENTAL_END_DATE,ACTUAL_RETURN_DATE,CAR_ID INTO START_DATE,END_DATE,ACTUAL_END_DATE,CARID
    FROM RENTAL WHERE RENTALID = RENTAL_ID;
    IF (PAY_METHOD IS NULL) THEN
    PAY_STATUS := 'Pending';
    PAYMENT_DATE := NULL;
    ELSE 
    PAYMENT_DATE := ACTUAL_END_DATE;
    END IF;
    SELECT CAR_DAILY_HIRE_RATE,CAR_DAILY_PENALTY_RATE INTO CAR_HIRE_RATE,LATE_RATE
    FROM CAR WHERE CARID = CAR_ID;
    
    R_DURATION:= CALCULATE_DURATION(START_DATE,ACTUAL_END_DATE);
    RENTAL_COST:= CALCULATE_RENTAL_COST (R_DURATION,CAR_HIRE_RATE);
    EX_EQUIPMENT_COST := CALCUALTE_EX_EQUIPMENT_COST (RENTALID);
    
    IF (ACTUAL_END_DATE > END_DATE ) THEN
    LATE_DURATION:= CALCULATE_DURATION (END_DATE,ACTUAL_END_DATE);
    LATE_AMOUNT := CALCULATE_LATE_PENANLTY_COST (LATE_DURATION,LATE_RATE);  
    END IF;
    TOTAL_AMOUNT := RENTAL_COST+EX_EQUIPMENT_COST+LATE_AMOUNT;
    TOTAL_P_AMOUNT := CALCUALTE_COST_AFTER_DISCOUNT (TOTAL_AMOUNT,DIS_RATE);
    TOTAL_P_AMOUNT := CALCUALTE_COST_AFTER_VAT (TOTAL_P_AMOUNT,VAT_RATE);
    
    INSERT INTO INVOICE VALUES (InvoiceID_SEQ.NEXTVAL,RENTALID,RENTAL_COST,EX_EQUIPMENT_COST,
    LATE_AMOUNT,TOTAL_AMOUNT,DIS_RATE,VAT_RATE,TOTAL_P_AMOUNT,PAY_STATUS,PAY_METHOD,PAYMENT_DATE);
    
END PR_CREATE_RENTAL_INVOICE;

END INVOICE_PKG;
/
